version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${salephone_dbname}
    expose:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
      - ./db/salephone.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - salephone_dbname=${salephone_dbname}
      - db_host=${db_host}
    depends_on:
      - db

volumes:
  postgres_data: